export const SERVICES = {
  messages: "messageService",
  users: "userService",
  auth: "authService",
  config: "configService",
  session: "sessionService",
  chat: "chatService",
  store: "storeService",
  email: "emailService",
  usersDao: "usersDao",
  messagesDao: "messagesDao",
  chatsDao: "chatsDao",
  emailsDao: "emailsDao",
  sessionDao: "sessionDao",
};
